### ISSUE TITLE
Compression Upgrade Crash

### ISSUE THREAD

**Issue by Dr-WeiAL** [P3pp3rF1y/SophisticatedStorage#163]
This problem occurs when you hold down Shift and click on the item to make it go into the limited barrel
![image](https://user-images.githubusercontent.com/47446553/233669325-661202d6-ebec-486c-92b6-3feab0c4767d.png)
![image](https://user-images.githubusercontent.com/47446553/233669394-fd8a3045-fc06-4beb-9ce7-75312a541126.png)
(By this time the game has crashed)

I tested it separately and found it to be a conflict with twilightforest

[crash-2023-04-21_22.55.49-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/11296895/crash-2023-04-21_22.55.49-client.txt)

**Comment by P3pp3rF1y** [comment]
This looks like an issue with twilight forest + rubidium for some reason. Somehow it tries to get the color for one of the items from TF color handler and crashes there because the item isn't a block. But I don't understand why it would even trying that which leads me to believe that rubidium changes how item coloring works. Could you try without one of these mods / without both and see what it does?

**Comment by Dr-WeiAL** [comment]
After testing, and rubidium does not have a relationship, only the installation of sophisticatedstorage and twilightforest will also cause the game to crash
[crash-2023-04-23_20.35.07-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/11303736/crash-2023-04-23_20.35.07-client.txt)

Installing only sophisticatedstorage and only rubidium does not crash the game

**Comment by P3pp3rF1y** [comment]
have this fixed in dev

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
