### ISSUE TITLE
Pipes chest bug

### ISSUE THREAD

**Issue by bigenergy** [P3pp3rF1y/SophisticatedStorage#169]
1. If something is passed to a chest from this mod by a pipe, then it will only contain an item through Hwyla. [pic 1]
2. But there will be no resources in the chest itself. [pic 2]
3. But if you suck a pipe in an ordinary chest from minecraft, then the resource will appear. [pic 3-4]
4. If you break the chest, the resources will disappear

mod version: 1.19.2-0.6.29.335
![image](https://user-images.githubusercontent.com/17977139/234561678-7b54ef6a-85dc-4e97-915b-e812d5d836d6.png)
![image](https://user-images.githubusercontent.com/17977139/234561709-42eb7179-0a46-4ca8-9b6f-254e8228ada0.png)
![image](https://user-images.githubusercontent.com/17977139/234561733-7fce590c-27b7-4da4-aea6-d4b8ffb1c119.png)
![image](https://user-images.githubusercontent.com/17977139/234561752-2e47a632-9a24-4c19-9586-b450691292cb.png)

**Comment by P3pp3rF1y** [comment]
Just tested this in ATM8 modpack and works without any issues. So I will need more info on how to recreate this, but it's very likely you have some mod interaction going on there that causes the item loss for you.

**Comment by bigenergy** [comment]
> Только что проверил это в модпаке ATM8 и работает без проблем. Поэтому мне понадобится больше информации о том, как воссоздать это, но очень вероятно, что у вас там происходит какое-то взаимодействие с модом, которое приводит к потере предмета для вас.

I have the same modpack, strange..
I'll try to find more information

**Comment by P3pp3rF1y** [comment]
maybe you have upgraded the chest, moved it around using something or similar kind of interaction?

**Comment by bigenergy** [comment]
> maybe you have upgraded the chest, moved it around using something or similar kind of interaction?

no, both chests fresh off the workbench

**Comment by P3pp3rF1y** [comment]
I will need more info here as I am unable to recreate and thus there's nothing to fix here. Otherwise will just close.

**Comment by andrewjbennett** [comment]
I'm experiencing this too, on the ATM7Sky modpack.

It's like the chests have two separate inventories: one that you can access via the UI (opening the chest and putting items in/out), and a second one that you can access via pipes (piping items in/out, and holding down shift to see the contents with Hwyla). Usually they would both be the same inventory (so you can interact with a chest via pipes or the UI), but it seems like when this bug happens, the two inventories get separated.

For me, this originally didn't happen at all when making chests, but then ? something ? happened/changed, and now all of the sophisticated storage chests that I make are in this bugged state. This applies for both upgraded and non-upgraded chests (so e.g. if I make an oak chest with the oak planks and the redstone torch, or if I make that chest then add iron around it etc to make a more upgraded one).

However, I've found a workaround: when a chest is in this glitchy state, if I shift click on it (which picks the chest up, I'll see if I can find out which mod it is), and then place the chest back down somewhere, the two inventories are combined into one and the items show up in the UI + can be interacted with via pipes etc.

I wonder if it might be some weird interaction between the two mods? It's possible that the bug triggered for the first time (after which point all new chests I made were glitched) after I accidentally picked up some chest with shift+click: when I first started in the game the chests I created were fine, I know at some point I accidentally picked up a chest and put it back down again, and potentially it's been since then that my newly created chests have been glitchy.

**Comment by P3pp3rF1y** [comment]
yeah using carry on can potentially leave the previously existing inventory "intact" and when you place it down it would start with a new inventory. This can especially easily be the case when a pipe is already connected to the chest and you pick it up then because at that point the pipe may the chest inventory access cached and if carry on doesn't notify it of the change it will just think that the chest is still there and interact with now no longer existing chest. I will give that a test and see what's going on there.

**Comment by P3pp3rF1y** [comment]
just a quick question @andrewjbennett, did you also use mek pipes when this happened?

**Comment by andrewjbennett** [comment]
I first used the pipez item pipe, but also tried the mek ones and had the same behaviour

**Comment by P3pp3rF1y** [comment]
A few months back I fixed a bug that caused pipe like mods to think that storage is there even after it was removed so this should no longer happen.

**Comment by bbbbadger** [comment]
Is there a version of 1.19.2 where this issue is fixed? Unsure at what version this thread was about, but I am currently on the latest version of 1.19.2 (0.9.7.765) and still struggling with this issue.

**Comment by P3pp3rF1y** [comment]
> Is there a version of 1.19.2 where this issue is fixed? Unsure at what version this thread was about, but I am currently on the latest version of 1.19.2 (0.9.7.765) and still struggling with this issue.

Based on when that update took place I am pretty sure I did the same fix in 1.19.2 as well so if you're having some kind of issue like that please log that as separate one. At the same time I have to say that I don't support 1.19.2 with anything but critical fixes so if it's just mildly annoying it's unlikely I will fix it.
