### ISSUE TITLE
1.19.2 Forge - SMP server will not start, cites compression upgrade issues.

### ISSUE THREAD

**Issue by katubug** [P3pp3rF1y/SophisticatedStorage#200]
Hi! I'm having an issue with version sophisticatedcore-1.19.2-0.5.69.311 and sophisticatedstorage-1.19.2-0.8.27.448 in the 1.15.0 version of my Cottage Witch modpack, on our multiplayer server. Forge is version 43.2.8

We get this crash on startup: 
[crash-2023-06-12_17.51.40-server.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/11726657/crash-2023-06-12_17.51.40-server.txt)

This occurs both with the previous version of Storage/Core and the current ones. Help would be very appreciated!

**Comment by P3pp3rF1y** [comment]
Fixed this in the latest release that has now been approved on curseforge. Also recommend updating to latest sophisticatedcore as I apparently broke depositing into empty limited barrels (it would only allow to put the item into empty slot through gui, in world it just ignored that player tried to deposit anything). There's now new release of core that fixes that.

**Comment by P3pp3rF1y** [comment]
and I forgot to mention the source of the crash here - looks like some item that could be compressed before can no longer be compressed which caused one of the storages to have combination of item that can be compressed and item that can't be compressed in the slots managed by one compression upgrade. The fix makes it so that the upgrade simply doesn't try to do anything with compression in that case but still allows to access the items so that they can be taken out.
