### ISSUE TITLE
Limited Barrel crash world

### ISSUE THREAD

**Issue by JesusSoa** [P3pp3rF1y/SophisticatedStorage#203]
I was testing the mod and when I put the "limited diamond barrel" nothing happened, when interacting with it, the world crashes and does not stop opening leaving this error.

java.lang.NoSuchMethodError: 'boolean net.minecraft.client.renderer.block.model.BakedQuad.hasAmbientOcclusion()'

any idea why?

[crash-2023-06-19_10.40.06-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/11789870/crash-2023-06-19_10.40.06-client.txt)

**Comment by P3pp3rF1y** [comment]
yes, optifine crashed you just remove it and you are good.

**Comment by zinerith** [comment]
I would advise going to the sophisticated core config in your serverconfig folder and disabling all the limited barrels to prevent this. The limited barrels crash the game if optifine is installed (or vice versa idk), so you have to remove those barrels via the config or otherwise remove optifine.

**Comment by P3pp3rF1y** [comment]
it's all the barrels because optifine removes part of the forge code barrel rendering depends on and it's not the only one, there are multiple other mods that will crash if optifine is installed because of this exact same issue. So in this case definitely remove Optifine instead if you want to play with mods in general. You can use Rubidium instead @zinerith

**Comment by zinerith** [comment]
I don't have any issues with the mod and the most recent version of optifine for 1.19.2. I didn't use limited barrels at the time so thought OP was running into a bug with them specifically and optifine, but have since further tested and realized I don't have any issues at all with any of the barrels. 

So really, I wonder if OP updates to Optifine's most recent release for their version if that'll fix their bug?

**Comment by P3pp3rF1y** [comment]
you may have an older version of forge then because the issue here is that optifine is made for an older version of forge and breaks the newer addition that forge did.
