### ISSUE TITLE
Compacting into uncraftable items

### ISSUE THREAD

**Issue by Jophire** [P3pp3rF1y/SophisticatedStorage#253]
I used kubejs to remove the recipe for Quarks Sturdy Stone (9x cobblestone) since I am using a separate mod for compressed blocks.
Using JEI I can see that there is no way to craft Sturdy Stone, so I know the kubejs edit is working; however, the compacting upgrade is still outputing sturdy stone.

**Comment by P3pp3rF1y** [comment]
Compacting upgrade cannot make up recipes, it basically calls something called RecipeManager and asks it what can be crafted from the given set of items using registered recipes (which is the exact same thing that crafting table does). So in your case it calls RecipeManager with stone and gets Sturdy Stone back as craftable. I guess the only exception would be if you are somehow changing recipes on the fly because compacting upgrade keeps cache in memory of crafting recipes it already used however that cache would be created after you restart the game and I would think kubejs removes the recipe before you actually load the world and compacting upgrade has a chance to ask about recipes.

I have no idea if this is some kubejs issue, but not much I can do here. Will keep this open for a bit, but will likely just close.

**Comment by Jophire** [comment]
Understandable, will keep testing and see if it is a caching issue.
