### ISSUE TITLE
Using resource packs causes textures errors

### ISSUE THREAD

**Issue by Dr-WeiAL** [P3pp3rF1y/SophisticatedStorage#275]
At first I thought it was a Rubidium issue, and when I took the mod out on its own and tested it the problem persisted, which led me to switch my testing to the resource packs
The textures work fine when no texture modification packs are installed, but as soon as any texture modification pack is installed, the texture will get an error
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/47446553/8b5f842d-b6d6-46ff-bfc6-b3fa0dbcab13)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/47446553/197aeabe-932b-42c6-b185-ee81b151eea9)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/47446553/0b977272-97a1-439a-bce8-b8ee33312306)
This seems to return to normal after restarting the game

Minecraft version: 1.20.1
NeoForge version: 47.1.69

**Comment by P3pp3rF1y** [comment]
I am unable to recreate with sophisticated mods and a couple additional mods in the pack. So I am going to assume that you have  more mods in your modpack.
Can you recreate with just sophisticated? If not I will need you to narrow it down to what other mod needs to be in the modpack for this happen.

**Comment by Dr-WeiAL** [comment]
Yes, I only have the sophisticated mod in my test modpack
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/47446553/c5ef60b3-5242-45ce-afea-0f0f5646ff8a)
[latest.log](https://github.com/P3pp3rF1y/SophisticatedStorage/files/12445215/latest.log)

**Comment by P3pp3rF1y** [comment]
Could you share the resource pack then as I tried with one and everything was ok

**Comment by Dr-WeiAL** [comment]
https://modrinth.com/resourcepack/xekrsquarepattern
https://modrinth.com/resourcepack/alacrity

These two are used above

**Comment by TookUrSweetRoll** [comment]
**Edit: While taking screen shots and changing my GUI scale they fixed themselves in world. I restarted my client and now its fixed in JEI and Jade also. No clue.**

Same here.  It seems to be stealing texture from random mods. Spruce Iron Barrel looks like Large Soul Lantern from 'Dustrial Decor and Spruce Gold Barrel looks like Illuminant Block from Simply Lights.

It's just the barrels, and it is directional. Placing against a block in front of you gets a broken texture. Placing from above to a block below you, and vice versa, is normal. 

![2023-08-29_09 10 25](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29466666/071f0a29-1b56-46c9-853d-5f0189f6079e)

![2023-08-29_09 15 12](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/29466666/66c0b099-efb0-4010-9981-1696e62fa0a8)

**Comment by P3pp3rF1y** [comment]
The issue here is that I don't properly refresh cache when resource packs change. Have that fixed for next release. In the meantime restarting game after resource pack change should work

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version just released on curseforge
