### ISSUE TITLE
Hopper upgrade not working

### ISSUE THREAD

**Issue by igork2kta** [P3pp3rF1y/SophisticatedStorage#287]
The hopper upgrade is not pulling the items from top neither pushing them below. 
I tried all possible settings. The Advanced hopper upgrade works properly.

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/61879988/320e13b8-de42-45f1-9959-c518704940e3)

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/61879988/c61b4399-3da3-4da7-86ae-0bcd97d53eb8)

Mod version:
sophisticatedcore-1.19.2-0.5.87.417
sophisticatedstorage-1.19.2-0.8.43.598

**Comment by P3pp3rF1y** [comment]
The way that you have those barrels setup their top doesn't point up, but points to the one of the NWSE directions and because of that it will input from there and output to its bottom which is in the opposite direction. you would need to put the barrels with their tops up if you wanted the hopper upgrade to work in this configuration.

But please let me know if it doesn't work if you put them down that way.

**Comment by igork2kta** [comment]
I tried these ways and it still doesn't work. Am I doing it wrong? Items do not go to the middle chest neither from the middle to the bottom chest/barrel.

Thanks for the fast response!

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/61879988/3140ddcc-714e-4228-aecb-f1ae18313dbe)

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/61879988/34112c4c-46c5-455e-a144-c66ce1ddb06f)

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/61879988/72f89d6b-4e17-44d7-b91c-655bbe5b273d)

**Comment by P3pp3rF1y** [comment]
alright that doesn't seem good then. I will check it out and very likely need to fix.

**Comment by igork2kta** [comment]
Now, it started working, ignoring the barrel setup haha, I really don't understand. Maybe an inttermitent bug? I'll keep playing and report if it happens again. Thanks for your attention and good work on the mod.
