### ISSUE TITLE
[1.19.2] [Question] Modifying Upgrade Recipes for Storages

### ISSUE THREAD

**Issue by 2ndkirbyever** [P3pp3rF1y/SophisticatedStorage#293]
I have been trying to modify the recipes for upgrading the storages (not the storage upgrade items) for quite some time.  KubeJS doesn't work because event.remove doesn't work with the recipes, and placing new data pack files for the upgrade recipes in my pack causes the recipes to bug out and be completely removed until I restart the game.

Is there a valid way to modify these recipes?

**Comment by P3pp3rF1y** [comment]
I am not any good with kubejs so I won't be able to tell you how exactly to modify this but there are modpacks that modify these and don't have an issue with that. Caching is done for these recipes so you may need to exit and reload the world when you change them. But I also made change fairly recently to reload cache when datapacks reload so that should work as well.

Anyway you will need to ask in kubejs for details or look at modpacks that override these recipes. The recipes have a special type because of nbt data that needs to be transferred but that's all that is special about them.
