### ISSUE TITLE
right clicking an item into a netherite shulkerbox on creative mode inventory deletes items 

### ISSUE THREAD

**Issue by eldritch-cookie** [P3pp3rF1y/SophisticatedStorage#320]
### Background Information

Minecraft Version: 1.20.1
Forge Version: 47.2.17
Mod Version: 0.8.62.671

### Steps to reproduce

1. open a new world on creative mode
2. cheat a netherite shulkerbox into hotbar
3. cheat any other storable item into hotbar
4. pickup other item into mouse 
5. right click on the netherite shulkerbox
6. at this point other item disappears and we expect the shulkerbox to contain it 
7. place and open shulkerbox to see no items inside

### Additional details

note that any other inventory tab works as normal so trying to reproduce while opening a chest or crafting table won't work.
i've tested and this bug occurs even with only sophisticated core + sophisticated storage

**Comment by P3pp3rF1y** [comment]
This is the weirdness of creative gui where changes only happen on client side and then the whole stack gets synchronized to server when in all other guis the change gets triggered on both sides. What happens here is that the item only gets inserted into contents on the client but because server doesn't have the contents updated it will still show nothing in shulker. Potentially I could add similar kind of synchronization for shulker box contents, but it would get complicated to detect when it should be synchronized to server and at the same time making sure it doesn't get synchronized in any other case.
So I am going to call this a creative screen "feature" and close as not to be fixed.
