### ISSUE TITLE
Duplication glitch with compression upgraded barrel through Refined Storage interface

### ISSUE THREAD

**Issue by Realworldjedi** [P3pp3rF1y/SophisticatedStorage#355]
Playing on Craft to Exile 2 0.5.2b
https://www.curseforge.com/minecraft/modpacks/craft-to-exile-2

I'm not sure this is limited to refined storage as I was able to do it two ways.

1st- when connected to a compression barrel if your character inventory has no slots available you can use a crafting grid and craft the higher block infinitely. As an example if you have a limited barrel III with iron nuggets/compression, you can use the RS crafting grid to craft iron ingots which then instantly changes the number of ingots and nuggets by decreasing the nuggets but at the same time increasing it 2fold.

2nd- not sure if I could replicate this one but I used packing tape on a barrel with copper/copper block. Then removed the compression upgrade and it still showed the same amount of blocks and nuggets, again 2fold increase.

**Comment by P3pp3rF1y** [comment]
The first one looks like an issue I already heard about where RS doesn't properly extract from inventories where it tries to extract more than a usual max stack size when api clearly says only max stack size can be extracted. So that one needs to be fixed on RS side. 

And I am unable to recreate the issue with packing tape and compression upgrade in barrel would need steps to recreate that issue.

**Comment by P3pp3rF1y** [comment]
closing as one issue is on RS side and there was no additional info provided on how to recreate the other one
