### ISSUE TITLE
Storage controller bug

### ISSUE THREAD

**Issue by waldmannl** [P3pp3rF1y/SophisticatedStorage#357]
First of all, the bug was on a server.

If we put a storage controller down and we link limited acacia barrels to it, the controller won't work with all the barrels.

But there is one more interesting thing. Among the barrels, there is also a limited acacia barrel that can store four different items, but it is as if only half is connected to the controller. In other words, every item has free space in the barrel, but if I want to load them through the controller, it loads 2 items in the barrel and ignores 2 and leaves it in the inventory.

**Comment by P3pp3rF1y** [comment]
You have debug tool that you can cheat in which will show you all storages connected to controller. 

When you say that it only loads 2 items what is it that you mean - are you right clicking controller with those items in hand / inventory? Or are you inserting these using vanilla hopper?

**Comment by waldmannl** [comment]
Yes i'm right clicking the controller with bare hands, with the items in my inventory.

**Comment by P3pp3rF1y** [comment]
what does debug tool show you? are you double right clicking the controller or single right clicking? and could you show screenshot of your setup when you have debug tool in hand (so that it shows additional info)

**Comment by Batlh** [comment]
actually the same problem arrised for me too with the controller not able to link to anything... my solution that solved it somehow was piping the items through a hopper in the controller that somehow worked but i needed 3 hoppers for it actually to work....
and the area it distributes to is limited to like 5-8 blocks away from it in a circle shape but actually linking it with other storages further away is not possible the linking tool just refuses to work in that moment or generally spoken most of the time i tried to use it.
solved that problem with rf tools storage scanner but that is just bcz it was installed in atm 9 (latest avaiable modpack version 0.2.51 ) too...
the moment i come home i will send a screenshot in here with the debug stick (vanilla minecraft debug stick?) details what get shown.

**Comment by P3pp3rF1y** [comment]
@Batlh this is all very random, if you have steps I can use to recreate please share those, but otherwise it sounds like something is very wrong in your world. That said I have just fixed a linking bug that caused storage to not be linkable under certain conditions - in most usual conditions it was still possible to link them to controller but if there was already a storage at the exact same distance from controller you wouldn't be able to link another one at the same distance. 
Doesn't sound like what you're experiencing but thought I would mention here.

**Comment by Rev045** [comment]
Having an issue with the linking, so I have the following setup

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/49342134/ffbf0a34-b088-4245-b0d3-67981bac59dd)
to the south

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/49342134/d4b941eb-9a54-40c2-9f5f-4fa5709c0ac4)
to the east

in the south section, I have storage links under the middle of the barrel rows like so:
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/49342134/0132999b-3bb1-4d8a-bdbc-a9f19ee99ca1)

and they all link up properly, hurray, however, in the east section, using the same setup, placing the links in the middle of the rows, nothing happens when i right click to link.
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/49342134/a19e97f7-f6cd-44a6-a8f6-46bbdc65b3d0)

which sucks, but thats not all
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/49342134/f0119823-ccd0-45cb-9258-c729aee1ffcd)
I try linking with a different barrel, and it works!
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/49342134/70916499-7f8a-4f53-b21e-b7c41e0038dc)

But only until here?? 
So trying to work around it, I just try to see which ones allow me to link and which ones dont.

![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/49342134/b0c8ce37-1a4b-417c-8256-371f14a8cb7d)

eventually theyre all connected in this mess...but I do not think this is how they were meant to work.

**Comment by P3pp3rF1y** [comment]
@Revv1e are you on the latest version because that looks awful lot like issue that was fixed there

**Comment by Rev045** [comment]
sophisticatedbackpacks-1.20.1-3.20.3.1034.jar I believe, in atm9
Could you link me to the resolved issue? Im curious as to what exactly caused it
edit: nvm found the issue, updating too, any reason why it happened?
edit: its fine now, also i gave the wrong mod pfft, my bad, but yeah its working now, thanks!
