### ISSUE TITLE
Sophisticated Storage causing server crash

### ISSUE THREAD

**Issue by OddMetal2** [P3pp3rF1y/SophisticatedStorage#36]
[crash details](https://mclo.gs/pNVqVdL), upon futher tinkering the auto blast furnace has corrupted the entire world chunk

**Comment by OddMetal2** [comment]
Advanced Auto Black is causing the crash

**Comment by P3pp3rF1y** [comment]
I have this fixed in dev. In the meantime you can just add sophisticated backpacks to your pack and that will fix your issue. Basically a bit of code that was supposed to move to core stayed in backpacks code and because in my dev I have all 3 mods I have never noticed this issue. And most modpacks that add storage add backpacks as we hence why this is just the second report of the issue.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest releases for 1.18 and 1.19
