### ISSUE TITLE
Possible memory under certain conditions

### ISSUE THREAD

**Issue by Vadewolf** [P3pp3rF1y/SophisticatedStorage#370]
[latest.log](https://github.com/P3pp3rF1y/SophisticatedStorage/files/14540747/latest.log)

this is all the info ive got besides its not forge version related and the versions from 2/13/2024 and before dont cause it

**Comment by P3pp3rF1y** [comment]
That log doesn't show anything similar to the ones you have reported in SB, I am unable to recreate similar to Yummy who isn't either and the mod versions released since that date have been downloaded more than 10 thousand times and I find it hard to believe that no one who downloaded it is actually using the mod.

So it must be something specific to your modpack / to the setup that you have there and i definitely need more info on how to recreate.

**Comment by Vadewolf** [comment]
i need to know wat mods migh6t cause the issue then cause im legit out of ideas and to the point of honestly dropping SS since i cant use it anymore due to the world hang as much as it is a heck of a good mod

**Comment by P3pp3rF1y** [comment]
I don't know what mods can cause the issue as this is the first time I am hearing about an issue like that. What I need is info that can actually help me see what's going on (like some log that will show where it hangs or understanding how I can recreate the issue in my environment so that I can see what's doing it.

**Comment by Vadewolf** [comment]
well u have my mod list and it hangs when i click "save and exit" then it does the "saving world" bit and just hangs

**Comment by P3pp3rF1y** [comment]
The saving hanging was after all related to hopper upgrade deadlock and fix for that was released on CF a few days back as for the memory issue I am unable to recreate so I would need some info that shows me what is happening for you.

**Comment by Vadewolf** [comment]
thank for the fix on the save hang as for the memory issue i legit dont know wats causing it so that will probably go unlearned i guess
