### ISSUE TITLE
Compression upgrade on limited barrels not working as intended with storage controller

### ISSUE THREAD

**Issue by AnthoynHo** [P3pp3rF1y/SophisticatedStorage#400]
sophisticatedstorage-1.20.1-0.10.20.778
sophisticatedcore-1.20.1-0.6.18.597
Forge 47.2.20
Limited barrels with compression upgrade don't seem to work with Storage Controller.
When inputting blocks and nuggets into storage controller it will not input into a limited controller barrel with compression upgrade will only accept item if empty. Have tried with various tiers of barrel. If there is a full stack of blocks of a item in the limited barrel the storage controller will not accept the block or nugget form of the item them and will shunt them into a free spot if available. It will however accept ingots and only ingots into the limited storage barrel. Acts in a similar manner if compression upgrade is put into a chest and has item like smelted iron in the compression slots.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate so I will need description of your setup / steps to recreate. 

What I am doing is basically limited barrel with compression upgrade, put iron ingot in it so that it shows both block and nuggets. Now I have controller next to it and hopper pointing into it and hopper will happily insert iron block despite there being none in the barrel yet (because it only has 1 ingot in it).

**Comment by P3pp3rF1y** [comment]
closing given no follow up

**Comment by DrSigma4164** [comment]
Hi. Had the same problem, once the barrel has this upgrade it can't accept anything in a slot that already has something. I demonstrated this in the video below. I took hoppers as an example, but how about taking pipes that can transfer not one item at a time but several, say 8, then 8 items will be inserted first, and then everything will stop.
Also, the video did not show the moment that if we have a gold ingot and 9 nuggets, and we take away 1 nugget, and accordingly this ingot will disappear, then the system will add another ingot, and the number of nuggets will be 9+8. At this moment, nothing is written to the log files.
https://imgur.com/a/QuU5h1r

**Comment by P3pp3rF1y** [comment]
> Hi. Had the same problem, once the barrel has this upgrade it can't accept anything in a slot that already has something. I demonstrated this in the video below. I took hoppers as an example, but how about taking pipes that can transfer not one item at a time but several, say 8, then 8 items will be inserted first, and then everything will stop. Also, the video did not show the moment that if we have a gold ingot and 9 nuggets, and we take away 1 nugget, and accordingly this ingot will disappear, then the system will add another ingot, and the number of nuggets will be 9+8. At this moment, nothing is written to the log files. https://imgur.com/a/QuU5h1r

First of all please open a new issue, you are lucky I noticed the notification because otherwise I don't look at closed issues. Second when or actually even before you create it make sure that you are able to recreate with just sophisticated storage or figure out what mod is causing this behavior and include versions of the mods as well. I certainly can't recreate the behavior so it's definitely some mod interaction happening for you.
