### ISSUE TITLE
Game crashing due to "rendering item" issue.

### ISSUE THREAD

**Issue by AriDaWaterNymph** [P3pp3rF1y/SophisticatedStorage#432]
My game crashes every time I bring up a sophisticated storage chest in JEI or craft them. The only thing that fixed it was to uninstall this mod entirely. I am playing a modpack so I'm not 100% sure if its this mod that is the problem but it's the only one that seems to give me trouble. 

Modpack: Cottage Witch 1.16.9
Minecraft Version: 1.19.2
Mod Version: 1.19.2-0.9.7.765

Crash Reports:
[crash-2024-06-08_22.51.46-client.txt](https://github.com/user-attachments/files/15750593/crash-2024-06-08_22.51.46-client.txt)
[crash-2024-06-08_23.24.03-client.txt](https://github.com/user-attachments/files/15750594/crash-2024-06-08_23.24.03-client.txt)

**Comment by P3pp3rF1y** [comment]
I am sure it's not sophisticated storage by itself because these are some of the most basic flows that I always go through when testing and players encounter in game so I would have heard about that a very long time ago (also just double checked in pack with sophisticated storage and JEI and everything works). 
The only thing I can figure out from these crash logs is that someone was trying to override chest textures and haven't provided all info which is now crashing the game. So this one is either for the modpack maker who is adding the customization or I would need to understand which mod combination is causing this and I don't mean the whole modpack, I mean the minimal set of mods with which I can recreate the issue.

**Comment by AriDaWaterNymph** [comment]
Oh! That being the case, I know exactly what the issue is. It's a custom texture pack that was made so that the chests would match Mizunos but it's for a different minecraft version and I forgot I had it enabled. Thank you!
