### ISSUE TITLE
Allow for rotating already placed chests and barrels

### ISSUE THREAD

**Issue by psml-imeji** [P3pp3rF1y/SophisticatedStorage#439]
Since the Limited Barrels only accepts items from its "front" face, it would be tricky to place the blocks in the right direction without breaking the nearby storages if we cannot just rotating them.

**Comment by P3pp3rF1y** [comment]
You can use packing tape and move it to new rotation and honestly I don't see why the rotation would need to be so often to require supporting rotation in place. Perhaps if you can explain your case more I may reconsider but otherwise I am going to close as something that's supported with the help of packing tape

**Comment by P3pp3rF1y** [comment]
closing, given no response
