### ISSUE TITLE
Crafting RS storage parts in sophisticated storage barrel with crafting upgrade Crash 

### ISSUE THREAD

**Issue by ChosenArchitect** [P3pp3rF1y/SophisticatedStorage#450]
Issue reported:
https://github.com/ChosenArchitect/Project-Architect-2/issues/20

Crash log:
https://mclo.gs/tucQV0v

Minecraft Version: 1.20.1
Forge: 47.3.0
Mod Version: 1.20.1-0.10.25.804
Core Version: 1.20.1-0.69.22.611

**Comment by James103** [comment]
Given the crash report, this is likely the same issue as https://github.com/P3pp3rF1y/SophisticatedCore/issues/236, as I got a similar crash while crafting Mekanism wind turbines inside a crafting table upgrade attached to a Sophisticated Backpack.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate trying to craft all kinds of RS parts so it's very likely an interaction with another mod that inserts something in crafting logic that makes the recipes try to leave items in slots of crafting grid that don't exist. However I have added a bit of logic into crafting upgrade so that instead of crashing it logs error if this happens and drops the extra items.

**Comment by P3pp3rF1y** [comment]
Fixed this in a release several weeks back just didn't close back then
