### ISSUE TITLE
Carry On compatibility issue

### ISSUE THREAD

**Issue by LioxAcc** [P3pp3rF1y/SophisticatedStorage#452]
Forge 1.20.1 - 47.3.5

sophisticatedcore-1.20.1-0.6.22.611
sophisticatedstorage-1.20.1-0.10.25.804
carryon-forge-1.20.1-2.1.2.7

(All mods are in their latest version)

When grabbing one of the 2 parts of a double chest, all the contents of the chest falls to the ground, also when repositioning it, you can't use the chest (I solved it by grabbing it and repositioning it on the ground).
In addition to this 
When holding a chest, it cannot be repositioned next to another one to make a double chest.

https://imgur.com/ktrfk8G

**Comment by Sazuzaki** [comment]
Can confirm.

**Comment by P3pp3rF1y** [comment]
So dropping contents if picking up the right part is correct - items are actually stored in one central storage that gets saved in the left part so when I detect that right part was removed using other means than normal means its state is invalid because it's holding more slots than it is allowed to and only thing that can be done is drop them on the ground. But anyway even if this was stored half and half the item access would still need to see everything so that hoppers and pipes can access all contents and because of that mods like carryon if they had time to look into item access wouldn't be able to determine which stacks are stored in the right part of the double chest and would likely duplicate items or I would have to prevent them from having time to look into item access and still drop items on the ground. 

As for the broken chest after it's placed on the ground I was going to take a look at this if there's anything I can do about that, but I wasn't able to pickup the chest with carry on and found out that it by default includes sophisticated chest in list of blocks that are not supposed to be picked up. So I am closing this as something that I am not going to worry about given that carry on isn't supposed to work on sophisticated chests.
