### ISSUE TITLE
Compacting upgrade sometimes not compacting automatically.

### ISSUE THREAD

**Issue by therocki** [P3pp3rF1y/SophisticatedStorage#453]
Minecraft Version: 1.20.4
Neoforge Version: 20.4.237
Modpack: FTB Neotech 1.6.0
Sophisticated Storage: 0.10.24
Sophisticated Core: 0.6.21

When I'm using compacting upgrade in limited barrels, it sometimes wont compact. They have proper reversable crafting recipes. It will compact when I manually place it into the GUI though.

![image](https://github.com/user-attachments/assets/006bf4b0-645a-479d-bbbc-d074ddbc75ff)
![image](https://github.com/user-attachments/assets/b7963bc2-bec5-49be-9a53-193dd6213dc1)

The compression upgrade does work though.

**Comment by therocki** [comment]
I actually did have the exact same thing happen with the compression upgrade. It is just rarer.

**Comment by therocki** [comment]
![2024-08-14_11 29 07](https://github.com/user-attachments/assets/be938fa3-c4a7-4a1f-a2e2-bd63d3e7041f)

**Comment by P3pp3rF1y** [comment]
This is a bit of caching problem related to custom recipes that I actually fixed in 1.20 and 1.21. 1.20.4 is a version that I don't support anymore with anything but potentially critical fixes and I am not going to spend time to fix and release fix just for this issue and will close as it's fixed in other longer term versions.
