### ISSUE TITLE
[Suggestion] Add a storage type/upgrade "Crate/Bundle"

### ISSUE THREAD

**Issue by Tortyash** [P3pp3rF1y/SophisticatedStorage#463]
This is a feature similar to QO Crates or Vanilla Bundles to storage a lot of different unstackable or 'low amount in stack' items.

The heavy modpacks make you collect a lot of different stuff that floods your chest, and even though default cap for crate is 640 items, which is 3 times less then a regular chest - if you start collecting unstackables - chest can only contain 27 items, which is 20 times less then a crate.

Introduction of bundles only fixed the flood problem with general items, but it still can't help with unstackables, and cannot be read by any storage system. Making Bundle Upgrade for a Backpack seems like a solution to both problems.

Which is why this seems like a good addition to Sophisticated Mods.

**Comment by P3pp3rF1y** [comment]
So for storing unstackables there are stack upgrades that can help with that, but I also have a plan to add "Unstacking Upgrade"(need to come up with a better name probably) which will decrease the max stack size per slot, but at the same time will make number of slots dynamic and count item size toward one "max item count per storage" number (similar to how RS has its limit on items) that will be calculated as [number of slots] x [reduced max stack size per slot]. 

Because of this plan I don't intend to implement either of the crate / bundle ideas.
