### ISSUE TITLE
A few questions about Sophisticated Storage

### ISSUE THREAD

**Issue by SirTwsted** [P3pp3rF1y/SophisticatedStorage#473]
1. - Are the chests blast proof?  If not, can you implement this by using Obsidian to protect chests from keeper's and alike?
      And one should be able to implement it's blast protection aka Obsidian implementation on any upgrade level if need be.
3. - If a person has AllTheModium mod installed, is it possible to make the chest space even larger?
       Basically, AllThemodium, Vibranium and Unobtainium are the 3 Ores within AllTheModium mod.
       And using such will increase the inventory space greatly,  with 

A. - AllTheModium increasing the storage by 25% of its Netherite max capacity,
B. - Vibranium increasing the storage by 50% of its Netherite max capacity.
and finally,
C. - Unobtaniun increasing the storage by 100% (basically doubling) of it's Netherite max capacity.

This is only if a person has ALLTheModium mod installed in their pack.
I don't know if this is possible to create or implement.  I am just asking.  😉👍

**Comment by P3pp3rF1y** [comment]
I am not really planning to have blast proof chests and regarding adding the AllTheModium I am not really interested in. Potentially I may make it possible for modpacks to add custom stack upgrades so that they can add whatever stack upgrade they want. That actually was requested as one of the features on discord so I will track this there.

**Comment by TheBedrockMaster** [comment]
It would be cool if there was something like an obsidian casing upgrade for chests to make them blast proof.
