### ISSUE TITLE
[1.21.1] Crashing when trying to load world

### ISSUE THREAD

**Issue by Zurkie** [P3pp3rF1y/SophisticatedStorage#502]
I've been unable to load my world, getting the following error:

[crash-2024-10-08_14.43.27-server.txt](https://github.com/user-attachments/files/17292818/crash-2024-10-08_14.43.27-server.txt)

Removing Sopisticated Storage removes the problem and loads the world back up. I don't know if this is a specifically Sophisticated Storage problem, but I figured it wouldn't hurt posting here to see if it's a part of a bigger problem

**Comment by P3pp3rF1y** [comment]
Would you know where you use compression upgrade and what kind of item(s) it is compressing? I find it puzzling that this would even happen but perhaps there's some specific combination of items that is causing this?

**Comment by Zurkie** [comment]
Yeah my bad, turns out it was because i had nether quartz being compressed. Removing compressor from that barrel seems to have fixed the issue

**Comment by P3pp3rF1y** [comment]
And it was just quartz? That is very odd to be honest and I am unable to recreate that also. Would be great if you were able to figure out the minimal set of mods with which this is happening.

**Comment by grifdail** [comment]
I'm having the same probleme.

Crash on load with what seem to be java.util.ConcurrentModificationException related to getUncompactingResult

[crash-2024-10-15_23.34.58-server.txt](https://github.com/user-attachments/files/17475406/crash-2024-10-15_23.34.58-server.txt)

[crash-2024-10-21_16.05.38-server.txt](https://github.com/user-attachments/files/17475432/crash-2024-10-21_16.05.38-server.txt)


For a while trying again after the first crash seem to fix the issue but now i use a NBT editor to teleport edit myself so that there no Sophisticated storage loaded when i open up the world.

I also took the time to compare mine and @Zurkie mod list...

What we have in common...

- Jade
- Patchouli
- amendments
- appleskin
- architectury
- athena
- cloth-config
- cupboard
- curios
- dummmmmmy
- friendsandfoes
- geckolib
- jei
- moonlight
- polymorph
- resourcefullib
- the_bumblezone
- supermartijn642configlib
- twilightforest
- waystones

And of course sophisticated, core, storage and backpack. I might have miss a few thing though... 

And obviously we are using different mod loader (forge vs Neoforge) and different version (1.21 vs 1.20.1)

**Comment by P3pp3rF1y** [comment]
I fixed this issue in 1.21 and 1.20 in releases a few weeks back.
