### ISSUE TITLE
[All versions]: Containers can't be inspected in spectator mode

### ISSUE THREAD

**Issue by macbrayne** [P3pp3rF1y/SophisticatedStorage#531]
## Expected Behaviour:
1. Fill chest / barrel with items
2. Switch to spectator mode (`/gamemode spectator`)
3. Right-click the container to inspect the items
4. A read-only version of the GUI will open which shows the items inside the container

(See https://minecraft.wiki/w/Spectator#GUIs)

## Actual Behaviour:
You can't interact with Sophisticated Storage containers in spectator mode.

## Versions affected:
Sophisticated Storage 0.8.46.624 using Sophisticated Core 0.5.98.458 on Forge 40.2.9 running on Minecraft 1.18.2
Sophisticated Storage 0.10.53 using Sophisticated Core 0.6.51 on NeoForge 21.1.77 running on Minecraft 1.21.1

**Comment by P3pp3rF1y** [comment]
Ok, I took a look at the implementation here. Just showing the storage with its slots that don't allow picking up stacks is fairly easy, but then preventing player from messing with upgrade switches, their settings and settings of storage overall + preventing pressing buttons all of that requires quite a few additional changes that would complicate the code quite a bit would be prone to get broken with additional features added because I definitely wouldn't spend much time testing spectator.

Based on that and the fact this is the very first time anyone mentioned the need to open storages in spectator I decided not to add this functionality. If I get more requests for this in the future or a really good justification why this should be a feature I may reconsider, but for now I am closing the issue.
