### ISSUE TITLE
There is a detection issue between the large chest and “Tom's Simple Storage Mod”

### ISSUE THREAD

**Issue by lostmyself8** [P3pp3rF1y/SophisticatedStorage#542]
The vanilla large chest was considered as one container by the connector of "[Tom's Simple Storage Mod](https://github.com/tom5454/Toms-Storage)", but "Soph" was considered as two and the stored items were also doubled (actually 1 but displayed as 2).

I'm not sure whose problem it is, but I have submitted issues on both sides.

![2024-11-25_21 37 22](https://github.com/user-attachments/assets/2f274f56-ae3b-40d0-b845-3127cd83f412)
![2024-11-25_21 37 12](https://github.com/user-attachments/assets/6850fed0-dc95-45be-a600-320b96a88e40)

**Comment by P3pp3rF1y** [comment]
Looking at their code I can't fix this on my side. For vanilla they just skip the second part of the chest, but they don't do it for mine. Even for vanilla it requires special handling and it would require it here as well, in fact almost identical so potentially they could add compat.

The problem is that both parts of the chest need to provide access to its full contents so that hoppers/pipes and other can work with all of that, but Toms then goes through both parts of the chest and counts slots from both as separate chests. Given that there's no way of knowing whether to provide some code that's trying to get contents with half of full inventory I can't fix on my side. In this case I could potentially check if there's block on the side from which the call originated (if the side is even provided), but as soon as you add second double chest right next to this I have no way of knowing that it's Tom's vs some other pipe mod trying to get contents.

**Comment by lostmyself8** [comment]
Oh, okay, thank you for your reply
