### ISSUE TITLE
关于limited_barrel

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedStorage#544]
When taking items from the limited_barrel, if you're not careful, you might accidentally dig out the barrel, causing the items inside to fall out. Is it possible to make it so that, without needing packing_tape, the items won't fall out after digging. Oralternatively, could the interaction interface be optimized so that when the crosshair is aimed at the item icon on the limited_barrel, holding the left mouse button won't trigger digging. The digging should only be triggered when the crosshair is aimed at the border and the left mouse button is held, just like in this image.
![129CE6A5_converted](https://github.com/user-attachments/assets/bffe2148-1911-41bf-b645-0aac7b8ecb0a)

**Comment by P3pp3rF1y** [comment]
you need to report this to the correct mod - That is a functional storage drawer

**Comment by ghost** [comment]
I hope you can optimize the storage system of the limited_barrel in Sophisticated Storage, for example, making it undiggable from the front (including in survival mode) and having it come with Packing_tape, similar to how Functional Storage works

**Comment by P3pp3rF1y** [comment]
Well limited barrels are undiggable from the front unless you have an axe in your hand when left clicking them. And there's a packing tape as well as a config setting that makes storages always drop packed. So to be honest I am not sure what you're talking about and would need clear description of an issue or something otherwise this ticket can just stay closed because I don't know of any issue here.

**Comment by ghost** [comment]
Sorry, it's my mistake. I didn't notice that I was wearing an item that boosts digging level, which made it so that I effectively had an axe even without holding one. Thanks for your explanation.
