### ISSUE TITLE
[1.20.1] Crash

### ISSUE THREAD

**Issue by Caio23364** [P3pp3rF1y/SophisticatedStorage#559]
https://mclo.gs/rXyuAo7
Minecraft Version: 1.20.1
Modloader: Forge 47.3.11

Mod versions:
Sophisticated Core 1.0.0.807
sophisticatedstorage-1.20.1-1.0.1.983.jar

When i open minecraft creative inventory on a server running mohist forge

Minecraft (client) crash and close

https://github.com/user-attachments/assets/5f52c608-1dde-46e7-896f-6d3ba2be906d

in the video, the minecraft has closed, i have pressed E to open inventory

**Comment by P3pp3rF1y** [comment]
I will need to see the actual crash log, please share that

**Comment by P3pp3rF1y** [comment]
actually never mind just noticed that it was included as the first thing in your report. Sorry somehow skipped over that

**Comment by P3pp3rF1y** [comment]
This one is super odd - I know for sure that paintbrush is registered properly. Does the server have the same version of sophisticated storage / core?

**Comment by Caio23364** [comment]
Everything is fine
Yes, the server have the same

the only solution I found was to go back to 977 of Sophiscated Storage
when I update, it gives this error again

**Comment by Caio23364** [comment]
The error is only on client
Crash only client

Singleplayer don`t have this error

**Comment by P3pp3rF1y** [comment]
Well that message basically means that paintbrush isn't registered on client, but it's registered exactly the same way that for example storage tool and all the upgrades are so there's something odd going on in your case. Either some mod is interfering in the registration or the only other explanation I have is that you have an older version of storage on client that doesn't have this pretty new item yet. 

Could you double check the versions and send me what they are both on client and server?
If they really are the same then I would need you to find out the minimal set of mods with which the issue happens so that I can then potentially take a look at how to fix. I am sure it doesn't happen with just sophisticated storage in the pack based on my testing.

**Comment by Caio23364** [comment]
I reinstalled everything and mysteriously it worked again in the latest version

I think it may have been ModsOptimizer that deleted the file

Thank you, and sorry for wasting your time

**Comment by P3pp3rF1y** [comment]
no worries, thanks for the info on mod optimizer, that may be useful in the future
