### ISSUE TITLE
[Question|Feature] Make `shift+rmb` upgrade work the same as double-click on controller

### ISSUE THREAD

**Issue by Danipulok** [P3pp3rF1y/SophisticatedStorage#567]
**Mods versions:**
```
sophisticatedbackpacks-1.20.1-3.20.17.1150
sophisticatedcore-1.20.1-1.0.0.807
sophisticatedstorage-1.20.1-1.0.1.983
```

**Steps to reproduce:**
1. Setup controller
2. Link it to a few double chests

**Current behavior:**
- With just double click, it empties inventory with only known items. So for example, if there's no `netherite` in the chests, `netherite` will remain in the inventory.
- With backpack upgrade to move all items to the external storage, it moves actually ALL items, even ones that are not known yet (not present in the storages)

**Question:**
Is it expected for it to work like this?
It seems to me it would be more intuitive if it worked the same as double-click, but just the whole backpack, no?
Because I, for example, really like that it moves only _known_ items on double-click, and I can manually add 'unknown' items where I want to the suitable chests. But when I use it with backpack upgrade, it moves even 'unknown' items to the chests...
Is there any way to configure it or plans to make it work the same?

**Comment by P3pp3rF1y** [comment]
You don't mention the upgrade name, but I assume it's deposit and by default what you're describing is the expected behavior. You can however set deposit to match target inventories contents and only deposit what already exists in there. 
One thing you need to keep in mind that if you're using deposit upgrade it's the upgrade depositing it to inventory and controller just happens to be a big inventory to it, but it's still the upgrade that decides on the rules and you have filter options you can setup for it. It's only when you use empty hand that it's controller taking items from the player.

**Comment by Danipulok** [comment]
Got it!
Thank you very much for the quick and detailed response!

This exact option seems to be working for me:
![image](https://github.com/user-attachments/assets/800c9c80-f6db-4afe-a0eb-0875058ed2f9)
With other second filters (like `mods`, `tags`, it doesn't seem to be working as I expected)

Just in case someone happens to stumble on this issue
Thank you a lot, again!
Merry Christmas!
