### ISSUE TITLE
Feature Request: JEI + Crafting

### ISSUE THREAD

**Issue by Saphrym** [P3pp3rF1y/SophisticatedStorage#61]
I was testing out storage for my modpack last night and tried crafting using the crafting upgrade and there was no + button through the JEI interface. Would it be possible to get the + crafting working in the storage ui so we can easily craft from the contents of a storage?

**Comment by P3pp3rF1y** [comment]
Which version are you using Saph?

**Comment by 13ofDragons** [comment]
Latest for 1.18.2: 
![image](https://user-images.githubusercontent.com/8853222/185669192-bf046ff3-d275-4bd2-952f-83883768cff0.png)

**Comment by EnderMelody** [comment]
it seems like the chest tier upgrades specifically are missing from jei. the recipe to create the initial SS chest shows up, but its too hard to find among all the other storage types and it doesnt show the use for it to upgrade tiers either. the only recipes that are shown are the dyes.

**Comment by 13ofDragons** [comment]
> it seems like the chest tier upgrades specifically are missing from jei. the recipe to create the initial SS chest shows up, but its too hard to find among all the other storage types and it doesnt show the use for it to upgrade tiers either. the only recipes that are shown are the dyes.

Last I looked the tier upgrades had a recipe and you use those to upgrade them in place.  But yes, I don't see recipes for the higher tier chests at this point.

**Comment by P3pp3rF1y** [comment]
@EnderMelody the og issue here is that + sign doesn't show up in JEI so that any recipe could be filled in crafting upgrade's gui. So that's very different from what you're referring to. For your cases specifically could you report it separately and provide more info? Also from quickly thinking about that one it's likely a modpack issue because all of the recipes show up correctly for me so trying it first with just sophisticated mods to confirm that it's not a modpack issue / following up with modpack creator if it is would be likely next steps.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version on CF
