### ISSUE TITLE
Having a crash when rendering Sophisticated Storage items through NEI

### ISSUE THREAD

**Issue by AchlysShade** [P3pp3rF1y/SophisticatedStorage#77]
I crashed when I loaded into the server and then searched "@stora" in nei. As soon as sophisticated storage's items were shown my client instantly exited the server and crashed, giving me the included report, the server didn't crash or have any backlash at all.
Was having issues running a particular set of mods and after alot of digging it seems that storagecore was the most likely culprit. 

[crash-2022-09-09_15.49.41-client.txt](https://github.com/P3pp3rF1y/SophisticatedStorage/files/9539157/crash-2022-09-09_15.49.41-client.txt)

**Comment by P3pp3rF1y** [comment]
You need to update sophisticated storage to the latest given that you have the latest core

**Comment by AchlysShade** [comment]
I was using the newest versions of both Sophisticated Storage, Core, and
Backpack. Even with that I was having repeated crashes on rendering the
Storage items. If I use the incorrect Core mod version then it let's you
know when attempting to even boot.

**Comment by P3pp3rF1y** [comment]
as I said you have incorrect storage version - yours is `1.18.2-0.5.1.107` when the latest is `1.18.2-0.5.11.137`. And mc won't tell you anything about that because that old version expects version of core higher than the version of core that existed at the time which the latest version of core is always going to be highest. And there's no way I can prevent that other than always locking core version to only a specific one and having to release new versions of backpacks and storage any time I only make a change in core which I don't think anyone wants.

**Comment by AchlysShade** [comment]
Alright, I'll run a double check and test on it just incase. Thanks for the
assistance and patience.
